### ISSUE TITLE
new orleans pd

### ISSUE THREAD

**Issue by ayyubibrahimi** [ipno-llead/processing#133]
Hey @pckhoi 

I can't remember if you had issues with matching the New Orleans PD roster that we received from IPM with the rosters that we received from the new Orleans CSD. I can only remember that the matching was poor between the rosters that we received directly from the New Orleans PD with the rosters that we received from the New Orleans civil service division. I ask because it would be ideal to map salary data from the CSD table onto the IPM table. Any recollection?

**Comment by pckhoi** [comment]
I don't think there was anything in particular about the data from NOPD or NO CSD that made matching too difficult. The feeling was that the data from IPM was much more complete and even come with complaints data so it was much more efficient to just ignore data from other sources. We have come a long way since then so we will probably be more successful this time around integrating these data. Please go ahead.
