### ISSUE TITLE
wrgl new release

### ISSUE THREAD

**Issue by ayyubibrahimi** [ipno-llead/processing#444]
Hey @pckhoi moving the email chain here. No luck running `pull`/receiving a browser prompt. Please see below. Thanks!

```
ayyubi@DESKTOP-BLLRMEO:/mnt/c/Users/PC/Desktop/llead/processing$ sudo bash -c 'curl -L https://github.com/wrgl/wrgl/releases/download/v0.12.10/install.sh | bash'
[sudo] password for ayyubi: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  2864  100  2864    0     0    898      0  0:00:03  0:00:03 --:--:--  2813
Downloading: https://github.com/wrgl/wrgl/releases/download/v0.12.10/wrgl-linux-amd64.tar.gz
Installing wrgl to /usr/local/bin.
ayyubi@DESKTOP-BLLRMEO:/mnt/c/Users/PC/Desktop/llead/processing$ wrgl pull --all
Pulling branches 0 / 212 [                                                                                                                            ] 0 %  0s
error fetching objects: error poping haves: GetCommit 4e5024d3b541cfc1afa632a9ab7c1ebc error: key not found
ayyubi@DESKTOP-BLLRMEO:/mnt/c/Users/PC/Desktop/llead/processing$
```

**Comment by pckhoi** [comment]
So look like you're installing version 0.12. Why? Just use the incantation that I gave on Slack.

Second, pull will not ask you to login since the repo is public. But when you push, it will ask you to login.

**Comment by ayyubibrahimi** [comment]
Sorry. I meant to post what is below. I tried to download an earlier version after it failed, which is what you see above. 

```
ayyubi@DESKTOP-BLLRMEO:/mnt/c/Users/PC/Desktop/launch/processing$ sudo bash -c 'curl -L https://github.com/wrgl/wrgl/releases/latest/download/install.sh | bash'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100  2863  100  2863    0     0    784      0  0:00:03  0:00:03 --:--:--  5253
Downloading: https://github.com/wrgl/wrgl/releases/download/v0.13.4/wrgl-linux-amd64.tar.gz
Installing wrgl to /usr/local/bin.
ayyubi@DESKTOP-BLLRMEO:/mnt/c/Users/PC/Desktop/launch/processing$ wrgl pull --all
error fetching objects: error poping haves: GetCommit 4e5024d3b541cfc1afa632a9ab7c1ebc error: key not found
ayyubi@DESKTOP-BLLRMEO:/mnt/c/Users/PC/Desktop/launch/processing$ 
```

In the email you advised run `push` or `pull` for the browser prompt. Apologies for not also running push before. Here is what I receive when I run `push`.

```
ayyubi@DESKTOP-BLLRMEO:/mnt/c/Users/PC/Desktop/launch/processing$ sudo bash -c 'curl -L https://github.com/wrgl/wrgl/releases/latest/download/install.sh | bash'
[sudo] password for ayyubi: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2863  100  2863    0     0   1906      0  0:00:01  0:00:01 --:--:--  968k
Downloading: https://github.com/wrgl/wrgl/releases/download/v0.13.4/wrgl-linux-amd64.tar.gz
Installing wrgl to /usr/local/bin.
ayyubi@DESKTOP-BLLRMEO:/mnt/c/Users/PC/Desktop/launch/processing$ wrgl push
To https://wrgl.llead.co
no refspec specified
ayyubi@DESKTOP-BLLRMEO:/mnt/c/Users/PC/Desktop/launch/processing$ 
```

**Comment by pckhoi** [comment]
Sorry I should have explained clearer.

The general idea is that login instructions only appear when further authorized scopes are needed for the current action. When the repo is private, just running `wrgl pull` will suffice because the data is private, you have to log in even if you only want to read it. But when it is public, then you have to run `wrgl push` because this command actually modify the data.

You may ask why isn't there a command to log in, I would say if you log in and you don't do anything with the access token, then it is useless. How about logging in now and not having to worry about access token in the future? The problem is access token life time can be as long or as short as a Keycloak admin want it to be. Therefore it is better to just ask people to log in as needed.

Also you don't need to rerun installation before every command run. Only need to rerun it when there is a new release. Just follow the repository https://github.com/wrgl/wrgl to get notification when there is a new version.

So looks like there's an error with `wrgl pull`. I'm investigating atm.

Regarding `wrgl push`, if you run `wrgl push -h`, then it will show you usage and examples. Basically you need to specify a remote name and refspecs to update a remote. With the way that this ipno-llead/processing repository setup I don't think any manual push from the local is necessary. Unless you know what you're doing of course.

**Comment by pckhoi** [comment]
So I just run pull on my local from scratch and it appears to run correctly. Perhaps your local repo has corrupted data. Just reset the local repo like this:
```
rm -rf .wrgl && git checkout .wrgl && wrgl init
```
Then pull just like normal
```
wrgl pull --all
```

If you have unstable connection then it might crash, in which case just rerun until it succeed.

**Comment by ayyubibrahimi** [comment]
You were right. No luck after running

`rm -rf .wrgl && git checkout .wrgl && wrgl init`

and 

`wrgl pull --all`

I receive the error below during the multiple times that I tried to pull. I'll try running again at locations with hopefully more stable connections. 

`error fetching objects: error receiving objects: pr.ReadObject error: stream error: stream ID 15; INTERNAL_ERROR; received from peer`

**Comment by pckhoi** [comment]
Just in case it wasn't clear, you only need to reset the local repo once. To deal with unstable connection, just rerun `wrgl pull --all` again and again until it succeed. It should incrementally download blocks and so won't take too long.

**Comment by ayyubibrahimi** [comment]
That was clear. Thanks. Will scour for a better connection tomorrow.

**Comment by ayyubibrahimi** [comment]
I'm now having an issue with my space/still working on solving the space issue with the company. At any rate, this isn't anything to worry about in the immediate because I was able to commit `agency_reference_list.csv` table by integrating it into the pipeline versus manually committing it, which is what I had done in the past.

**Comment by pckhoi** [comment]
Glad to know that it is working for you. Yeah, ideally local development should only use minimal space.
