### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by ayyubibrahimi** [ipno-llead/processing#450]
Hi @huy-d-nguyen @baoea, as you are working on the new data pipeline I wanted to direct you to an example of a new event type that I would like to eventually introduce so that we can find a proper workflow for introducing new events. 

I have just opened PR #449 where I have added `report_date` as an event to the `event` table. These events are derived from a `use_of_force` incident, therefore, these events all have a corresponding `uof_uid`, in addition to an `event_uid`. You will see the proposed changes in the WRGL transaction [here](https://hub.wrgl.co/@ipno/r/data/tx/26412e9a-1988-4438-9f95-94ebf60f1ac0).  

Ideally, once a card is made for these events to be visualized on LLEAD, the card for these events will include `use_of_force_description` and `use_of_force_effective` as attributes, both of which are present in the `event` and the `use_of_force` tables.

**Comment by huy-d-nguyen** [comment]
Hi @ayyubibrahimi , for now our proposal has a section call Data validator (image below).
<img width="720" alt="image" src="https://user-images.githubusercontent.com/60863227/213611113-981299ba-7f5c-419e-93cc-75498d3ac22e.png">
We think this solution can deal with the new event adding problem. For example, we will mark the event kind as choices field, and it means that the event kind cannot have other values than the ones we have defined, and we will publish as a part of the validator api data. So that when we check the data, we will check whether the event `kind` has any value that haven't defined or not, if it has, we will raise the error and stop the process of importing. How do you feel about that? Please let us know if my explanation is not clear enough.

**Comment by ayyubibrahimi** [comment]
Awesome. Happy to merge this example if it is unnecessary.
